### PR TITLE
Update eclasses

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Noticed I was missing highlighting on an eclass so figured I'd just update them all :)

Got the list by doing:
```
$ cd /usr/portage/eclass
$ find -type f -name "*.eclass" -exec basename {} .eclass ';' | sort
```

### CODE REVIEW

**Comment by aegypius** [comment]
Thank you very much, I'll need to update the actual grammar file to get it working but it should not take too long.

**Comment by simonvanderveldt** [comment]
@aegypius Ohw, sorry about that, I didn't know another file also needed to be updated :|

**Comment by aegypius** [comment]
No problems, thanks anyway 😉

**Comment by simonvanderveldt** [comment]
Looking at the code I guess it's this list? https://github.com/aegypius/language-gentoo/blob/master/grammars/ebuild.cson#L175

I noticed there's some stuff in there to make it more flexible/variable like `apache-(2|module)`.
Wouldn't it be easier to convert the list in `resources/eclass.list` to a pipe separate string and put it there?

Or does the kind of deduplication that's in there now offer something that you won't get with this simpler way of doing it?

**Comment by aegypius** [comment]
Yes it's that regular expression that need to be updated. I guess we could use a command to generate the appropriate expression with the extracted list you updated.

The patterns like `apache_(2|module)` came from an older plugin I wrote years ago, I fixed the missing eclasses but this is not a requirement at all.

Sorry I haven't been able to update this PR.

**Comment by simonvanderveldt** [comment]
OK, if it's just that list I can update the PR to add them there as simple list separated by pipes (`|`). Would that be OK?

**Comment by aegypius** [comment]
(Sorry it seems that my reply by mail lost it's way here)

Yes, if you want to give it a try please do. These kind a regular expression are quite simple. Just enumerate the choice between parenthesis separated by pipes.

For example, to match "good" and "evil" you can write `'\\b\\s+(good|evil)'` in the begin field.

**Comment by aegypius** [comment]
@simonvanderveldt I manage to get a little time to merge this. Thanks for your contribution and patience ;)

**Comment by simonvanderveldt** [comment]
Awesome, thanks!

**Pull request merged**
